### ISSUE TITLE
AttributeError: module 'open3d_ros_helper' has no attribute 'rospc_to_o3dpc'

### ISSUE THREAD

**Issue by mkshah909** [SeungBack/open3d-ros-helper#3]
Installed package on ubuntu using pip.
My script imported the package correctly, but I tried to use it as shown on the pypi page example, and it was showing the error above. Don't really have experience with making python packages, so not sure what exactly to fix, seems like some small referencing issue.
For now I have manually copied the function from source, would be nice to not have to do that though.

**Comment by SeungBack** [comment]
How did you import the package? 
You should import the package by "from open3d_ros_helper import open3d_ros_helper" instead of "import open3d_ros_helper". 

You can use "rospc_to_o3dpc" function as follows:

```
from open3d_ros_helper import open3d_ros_helper as orh
import numpy as np

o3dpc = orh.rospc_to_o3dpc(some_ros_point_cloud) 
```

**Comment by mkshah909** [comment]
Ohh crap, I must've totally missed it. I'm pretty sure I was just trying "import open3d_ros_helper as orh", but I'll check, fix, and confirm here. Thanks a lot!
